### ISSUE TITLE
Incorrect composer install instuctions

### ISSUE THREAD

**Issue by adriankeenan** [TheSMSWorks/smsw-php-sdk#1]
In order to install the package with composer you must use the following, rather than what is currently in the readme.

```
{
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/TheSMSWorks/smsw-php-sdk.git"
        }
    ],
    "require": {
        "GIT_USER_ID/GIT_REPO_ID": "*@dev"
    }
}
```

Ideally GIT_USER_ID/GIT_REPO_ID would be changed to the real package name in this project's composer.json, so that it's obvious what we're requiring, but this does work.

**Comment by TheSMSWorks** [comment]
Thank you very much Adrian. We've added the correct URL to README.md.
