### ISSUE TITLE
Guzzlehttp/guzzle Versioning

### ISSUE THREAD

**Issue by bradleyking-dev** [TheSMSWorks/smsw-php-sdk#3]
In the composer.json can it be edited from "guzzlehttp/guzzle": "^6.2" to "guzzlehttp/guzzle": "^6.3.1|^7.0.1"

**Comment by stuartford** [comment]
+1 for this. Preventing upgrade to Laravel 8.

**Comment by TheSMSWorks** [comment]
Guzzle dependency now bumped to 7.3, now that we have moved from swagger to OpenAPI generator.
