### ISSUE TITLE
name is missed in composer.json

### ISSUE THREAD

**Issue by awhitenose** [TheSMSWorks/smsw-php-sdk#6]
"name" attribute is completely missed in composer.json making it impossible to use this as a repository in composer and produces the following error with any composer updates:

_Skipped branch master, Unknown package has no name defined ({"description":"The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts....._

**Comment by TheSMSWorks** [comment]
Name added. Thanks for the heads up.
